
#     
# 
# we are extending everything from java:8.0 image ...
FROM openjdk:16
MAINTAINER Nemesis# 
# Set environment
ENV JAVA_HOME /opt/jdk
ENV PATH ${PATH}:${JAVA_HOME}/bin
# COPY myJarFolder from local repository to the image
####COPY ./myJarFolder /usr/local/myJarFolder

#COPY path-to-your-application-jar path-to-webapps-in-docker-jar
COPY ubiquitous-system.jar /app/ubiquitous-system.jar
##cmd runs jar file in jvm
#CMD ["java", "-Djava.security.egd=file:/dev/./urandom","-jar","/app/ubiquitous-system.jar"]

# Start the image with the jar file as the entrypoint
ENTRYPOINT ["java", "-jar", "/app/ubiquitous-system.jar"]


# EOF

