/*
 *     
 * 
 */
package za.ac.cput.crud;

import java.awt.Image;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import za.ac.cput.bookshelf.AboutForm;
import za.ac.cput.bookshelf.BookingForm;
import za.ac.cput.settings.Configuration;
import za.ac.cput.settings.FrameSettings;
import za.ac.cput.settings.SystemSettingsCompanyProfileForm;
import za.ac.cput.settings.SystemSettingsConectionsForm;

/**
 *
 * @author Peter Buckingham
 */
public class CRUDGui extends javax.swing.JFrame {

    /**
     *
     */
    public static User user;
    public int userAccessLevel ;


    /**
     * Creates new form CRUDGui
     *
     * @param user
     */
    public CRUDGui(User user) {
        //constructor with signature : public CRUDGui(User readUser);
        //constructor with parameters : User readUser
        //constructor description : Creates new form CRUDGui with readUser parameter , sets the title of the frame
        this.user = user;
        userAccessLevel = Integer.parseInt(user.getAccessLevel());
        System.out.println("User access level is : " + userAccessLevel);

        setTitle("Ubiquitous System" + " - " + "CRUD Control Panel");
        if (userAccessLevel > 0) {
            initComponents();
        } else {
            System.err.println("you do not have access to this, please contact the system admin!");
        }
        // initComponents();
    }

    /**
     *
     */
    public CRUDGui() {
        //constructor with signature : public CRUDGui();
        //constructor with parameters : none
        //constructor description : Creates new form CRUDGui with no parameters , creates some objects

        initComponents();
    }
    CreateUserForm createUserForm = new CreateUserForm(this, rootPaneCheckingEnabled);
    CreateBookForm createBookForm = new CreateBookForm();
    UpdateBookForm updateBookForm = new UpdateBookForm();
    UpdateUserForm updateUserForm = new UpdateUserForm();
    DisplayBookForm displayBookForm = new DisplayBookForm();

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonAddBook = new javax.swing.JButton();
        jButtonBookList = new javax.swing.JButton();
        jButtonUpdateBook = new javax.swing.JButton();
        jButtonAddUser = new javax.swing.JButton();
        jButtonUserList = new javax.swing.JButton();
        jButtonUpdateUser = new javax.swing.JButton();
        jButtonSearchUser = new javax.swing.JButton();
        jButtonSearchBook = new javax.swing.JButton();
        jButtonDeleteBook = new javax.swing.JButton();
        jButtonDeleteUser = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jPanelTop = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelImagePanelBanner = new javax.swing.JPanel();
        jLabelPictureBanner = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile1 = new javax.swing.JMenu();
        jMenuItemNewLoan = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemCRUD = new javax.swing.JMenuItem();
        jMenuSettings = new javax.swing.JMenu();
        jMenuItemConnectivity = new javax.swing.JMenuItem();
        jMenuItemCompanyProfile = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();
        jMenuItemHelpWiki = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD - Operations -  Menu");
        setIconImage(displayFrameImageIcon());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                windowClosingHandler(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(250, 249, 246));

        jPanel2.setBackground(new java.awt.Color(192, 192, 192));

        jButtonAddBook.setText("Add Book ");
        jButtonAddBook.setToolTipText("Click to add book");
        jButtonAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBookActionPerformed(evt);
            }
        });

        jButtonBookList.setText("Book List");
        jButtonBookList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookListActionPerformed(evt);
            }
        });

        jButtonUpdateBook.setText("Update Book");
        jButtonUpdateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateBookActionPerformed(evt);
            }
        });

        jButtonAddUser.setText("Add User");
        jButtonAddUser.setToolTipText("Click to add users");
        jButtonAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddUserActionPerformed(evt);
            }
        });

        jButtonUserList.setText("User List");
        jButtonUserList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserListActionPerformed(evt);
            }
        });

        jButtonUpdateUser.setText("Update User");
        jButtonUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateUserActionPerformed(evt);
            }
        });

        jButtonSearchUser.setText("Search User");
        jButtonSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchUserActionPerformed(evt);
            }
        });

        jButtonSearchBook.setText("Search Book");
        jButtonSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchBookActionPerformed(evt);
            }
        });

        jButtonDeleteBook.setText("Delete Book");
        jButtonDeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteBookActionPerformed(evt);
            }
        });

        jButtonDeleteUser.setText("Delete User");
        jButtonDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAddBook, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addGap(18, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBookList, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jButtonUserList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonUpdateBook, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDeleteUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSearchUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSearchBook, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddBook)
                    .addComponent(jButtonBookList)
                    .addComponent(jButtonUpdateBook)
                    .addComponent(jButtonDeleteBook)
                    .addComponent(jButtonSearchBook))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddUser)
                    .addComponent(jButtonUserList)
                    .addComponent(jButtonUpdateUser)
                    .addComponent(jButtonDeleteUser)
                    .addComponent(jButtonSearchUser))
                .addGap(20, 20, 20))
        );

        jPanel3.setBackground(new java.awt.Color(192, 192, 192));

        jButtonCancel.setText("Cancel");
        jButtonCancel.setMaximumSize(new java.awt.Dimension(67, 67));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelTop.setBackground(new java.awt.Color(192, 192, 192));

        jLabel3.setBackground(new java.awt.Color(192, 192, 192));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Please select an action:");

        jPanelImagePanelBanner.setMaximumSize(new java.awt.Dimension(75, 75));

        jLabelPictureBanner.setBackground(new java.awt.Color(192, 192, 192));
        jLabelPictureBanner.setForeground(new java.awt.Color(192, 192, 192));
        jLabelPictureBanner.setIcon(new Configuration().displayLogoBannerFromConfig());
        jLabelPictureBanner.setMaximumSize(new java.awt.Dimension(75, 75));
        jLabelPictureBanner.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout jPanelImagePanelBannerLayout = new javax.swing.GroupLayout(jPanelImagePanelBanner);
        jPanelImagePanelBanner.setLayout(jPanelImagePanelBannerLayout);
        jPanelImagePanelBannerLayout.setHorizontalGroup(
            jPanelImagePanelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagePanelBannerLayout.createSequentialGroup()
                .addComponent(jLabelPictureBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelImagePanelBannerLayout.setVerticalGroup(
            jPanelImagePanelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagePanelBannerLayout.createSequentialGroup()
                .addComponent(jLabelPictureBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelImagePanelBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelImagePanelBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jMenuFile1.setMnemonic('F');
        jMenuFile1.setText("File");

        jMenuItemNewLoan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, 0));
        jMenuItemNewLoan.setMnemonic('L');
        jMenuItemNewLoan.setText("New Loan");
        jMenuItemNewLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewLoanActionPerformed(evt);
            }
        });
        jMenuFile1.add(jMenuItemNewLoan);

        jMenuBar1.add(jMenuFile1);

        jMenuEdit.setMnemonic('e');
        jMenuEdit.setText("Edit");

        jMenuItemCRUD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        jMenuItemCRUD.setMnemonic('c');
        jMenuItemCRUD.setText("CRUD");
        jMenuItemCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCRUDActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemCRUD);

        jMenuBar1.add(jMenuEdit);

        jMenuSettings.setMnemonic('S');
        jMenuSettings.setText("Settings");

        jMenuItemConnectivity.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        jMenuItemConnectivity.setMnemonic('c');
        jMenuItemConnectivity.setText("Connectivity");
        jMenuItemConnectivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConnectivityActionPerformed(evt);
            }
        });
        jMenuSettings.add(jMenuItemConnectivity);

        jMenuItemCompanyProfile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, 0));
        jMenuItemCompanyProfile.setMnemonic('P');
        jMenuItemCompanyProfile.setText("Company Profile");
        jMenuItemCompanyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCompanyProfileActionPerformed(evt);
            }
        });
        jMenuSettings.add(jMenuItemCompanyProfile);

        jMenuBar1.add(jMenuSettings);

        jMenuHelp.setMnemonic('h');
        jMenuHelp.setText("Help");

        jMenuItemAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        jMenuItemAbout.setMnemonic('a');
        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAbout);

        jMenuItemHelpWiki.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, 0));
        jMenuItemHelpWiki.setMnemonic('w');
        jMenuItemHelpWiki.setText("Help Wiki");
        jMenuItemHelpWiki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHelpWikiActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemHelpWiki);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteUserActionPerformed
        //JButtonDeleteUserActionPerformed method parameters : ActionEvent evt
        //jButtonDeleteUserActionPerformed method signature : public void jButtonDeleteUserActionPerformed(java.awt.event.ActionEvent evt)
        //JButtonDeleteUserActionPerformed method return type : void
        //JButtonDeleteUserActionPerformed method description : This method is called when the readUser clicks on the Delete User button. It deletes the readUser from the database.
        Delete delete = new Delete();
        delete.deleteUser();
    }//GEN-LAST:event_jButtonDeleteUserActionPerformed

    private void jButtonDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteBookActionPerformed
        //JButtonDeleteBookActionPerformed method parameters : ActionEvent evt
        //  JButtonDeleteBookActionPerformed method signature : void jButtonDeleteBookActionPerformed(java.awt.event.ActionEvent evt)
        //JButtonDeleteBookActionPerformed method return type : void
        //JButtonDeleteBookActionPerformed method description : This method is called when the readUser clicks on the Delete Book button. It deletes the book from the database.
        Delete delete = new Delete();
        delete.deleteBook();
    }//GEN-LAST:event_jButtonDeleteBookActionPerformed

    private void jButtonSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchBookActionPerformed
        //JButtonSearchBookActionPerformed method parameters : ActionEvent evt
        //JButtonSearchBookActionPerformed method signature : void jButtonSearchBookActionPerformed(java.awt.event.ActionEvent evt)
        //JButtonSearchBookActionPerformed method return type : void
        //JButtonSearchBookActionPerformed method description : This method is called when the readUser clicks on the Search Book button. It searches the book from the database.

        Read read = new Read();
        read.readBookByTitle();
    }//GEN-LAST:event_jButtonSearchBookActionPerformed

    private void jButtonSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchUserActionPerformed
        //  JButtonSearchUserActionPerformed method parameters : ActionEvent evt
        //JButtonSearchUserActionPerformed method signature : void jButtonSearchUserActionPerformed(java.awt.event.ActionEvent evt)
        //JButtonSearchUserActionPerformed method return type : void
        //JButtonSearchUserActionPerformed method description : This method is called when the readUser clicks on the Search User button. It searches the readUser from the database.

        Read read = new Read();
        read.readUserByName();
    }//GEN-LAST:event_jButtonSearchUserActionPerformed

    private void jButtonUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateUserActionPerformed
        //JButtonUpdateUserActionPerformed method parameters : ActionEvent evt
        //JButtonUpdateUserActionPerformed method signature : void jButtonUpdateUserActionPerformed(java.awt.event.ActionEvent evt)
        //JButtonUpdateUserActionPerformed method return type : void
        //JButtonUpdateUserActionPerformed method description : This method is called when the readUser clicks on the Update User button. It updates the readUser in the database.

        //find readUser  
        //update readUser
        Read read = new Read();
        User readUser = read.readUserByName();
        updateUserForm = new UpdateUserForm(readUser);
        updateUserForm.setVisible(rootPaneCheckingEnabled);
        Update update = new Update();

    }//GEN-LAST:event_jButtonUpdateUserActionPerformed

    private void jButtonUserListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserListActionPerformed
        //JButtonUserListActionPerformed method parameters : ActionEvent evt
        //JButtonUserListActionPerformed method signature : void jButtonUserListActionPerformed(java.awt.event.ActionEvent evt)
        //JButtonUserListActionPerformed method return type : void
        //JButtonUserListActionPerformed method description : This method is called when the readUser clicks on the User List button. It displays the list of users in the database.

        Read read = new Read();
        UserListForm userListForm = new UserListForm(read.readAllUsers());
        userListForm.setVisible(rootPaneCheckingEnabled);
        userListForm.setAlwaysOnTop(rootPaneCheckingEnabled);


    }//GEN-LAST:event_jButtonUserListActionPerformed

    private void jButtonAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddUserActionPerformed
        //JButtonAddUserActionPerformed method parameters : ActionEvent evt
        //JButtonAddUserActionPerformed method signature : void jButtonAddUserActionPerformed(java.awt.event.ActionEvent evt)
        //JButtonAddUserActionPerformed method return type : void
        //JButtonAddUserActionPerformed method description : This method is called when the readUser clicks on the Add User button. It adds the readUser to the database.

        createUserForm.setVisible(rootPaneCheckingEnabled);
        createUserForm.setAlwaysOnTop(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jButtonAddUserActionPerformed

    private void jButtonUpdateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateBookActionPerformed
        //JButtonUpdateBookActionPerformed method parameters : ActionEvent evt
        //JButtonUpdateBookActionPerformed method signature : void jButtonUpdateBookActionPerformed(java.awt.event.ActionEvent evt)
        //JButtonUpdateBookActionPerformed method return type : void
        //JButtonUpdateBookActionPerformed method description : This method is called when the readUser clicks on the Update Book button. It updates the book in the database.

        //read book 
        Read read = new Read();
        Book book = read.readBookByTitle();
        //updateBookForm.get
        updateBookForm = new UpdateBookForm(book);
        //   updateBookForm = new UpdateBookForm(book.getTitle(), book.getSubTitle(), book.getAuthors(), book.getDescription(), book.getRating(), book.getImageLink());
        updateBookForm.setVisible(rootPaneCheckingEnabled);
        //updateBookForm.setAlwaysOnTop(rootPaneCheckingEnabled);

        //if book found
        //display boo update form and populate with data from DB
        //if readUser presses update button then push to DB (update)
        ////////////// Update update = new Update();
        ////////////// update.updateBook();
        // if book found then display book details with form

    }//GEN-LAST:event_jButtonUpdateBookActionPerformed
    /**
     *
     * @apiNote This method is called when the user clicks on the Book List button. It displays the list of books in the database, and the user can select a book to view the details.
     * @param evt ActionEvent evt
     */
    private void jButtonBookListActionPerformed(java.awt.event.ActionEvent evt) {
        //JButtonBookListActionPerformed method parameters : ActionEvent evt
        //JButtonBookListActionPerformed method signature : void jButtonBookListActionPerformed(java.awt.event.ActionEvent evt)
        //JButtonBookListActionPerformed method return type : void
        //JButtonBookListActionPerformed method description : This method is called when the readUser clicks on the Book List button. It displays the list of books in the database.
        Read read = new Read();
        //read.readAllBooks();
        BookListForm bookListForm = new BookListForm(read.readAllBooks());
        bookListForm.setVisible(true);
        bookListForm.setAutoRequestFocus(rootPaneCheckingEnabled);
    }

    /**
     *
     * @apiNote This method is called when the user clicks on the Add Book button. It adds the book to the database.
     * @param evt ActionEvent evt
     */
    private void jButtonAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBookActionPerformed

        //JButtonAddBookActionPerformed method parameters : ActionEvent evt
        //JButtonAddBookActionPerformed method signature : void jButtonAddBookActionPerformed(java.awt.event.ActionEvent evt)
        //JButtonAddBookActionPerformed method return type : void
        //JButtonAddBookActionPerformed method description : This method is called when the readUser clicks on the Add Book button. It adds the book to the database.
        createBookForm.setVisible(rootPaneCheckingEnabled);
        createBookForm.setAlwaysOnTop(rootPaneCheckingEnabled);
        //  Create create = new Create();
        //create.createBook();/////

    }//GEN-LAST:event_jButtonAddBookActionPerformed
    /**
     *
     * @apiNote This method is called when the user clicks on the cancel button, and it closes the current form.
     * @param evt ActionEvent evt
     */
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        //  jButtonCancelActionPerformed method parameters : ActionEvent evt
        //  jButtonCancelActionPerformed method signature : void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt)
        //  jButtonCancelActionPerformed method return type : void
        //  jButtonCancelActionPerformed method description : This method is called when the readUser clicks on the Cancel button. It closes the application.

        this.setVisible(false);
        this.dispose();
        //  exit();

    }//GEN-LAST:event_jButtonCancelActionPerformed
    /**
     *
     * @apiNote windowClosing method this method is called when the user clicks on the close button on the form. It updates the user in the database.
     * @param evt ActionEvent evt
     */
    private void windowClosingHandler(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosingHandler
        //  windowClosingHandler method parameters : WindowEvent evt
        //  windowClosingHandler method signature : void windowClosingHandler(java.awt.event.WindowEvent evt)
        //  windowClosingHandler method return type : void
        //  windowClosingHandler method description : This method is called when the readUser clicks on the X button. It closes the application.

        this.setVisible(false);
        this.dispose();
        //  exit();


    }//GEN-LAST:event_windowClosingHandler

    private void jMenuItemCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCRUDActionPerformed
        // jMenuItemCRUDActionPerformed method parameters : ActionEvent evt
        // jMenuItemCRUDActionPerformed method signature : void jMenuItemCRUDActionPerformed(java.awt.event.ActionEvent evt)
        // jMenuItemCRUDActionPerformed method return type : void
        // jMenuItemCRUDActionPerformed method description : This method is called when the readUser clicks on the CRUD button. It displays the CRUD form.

        CRUDGui cRUDGui = new CRUDGui(user);
        cRUDGui.setVisible(rootPaneCheckingEnabled);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItemCRUDActionPerformed

    private void jMenuItemConnectivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConnectivityActionPerformed
        //  jMenuItemConnectivityActionPerformed method parameters : ActionEvent evt
        //  jMenuItemConnectivityActionPerformed method signature : void jMenuItemConnectivityActionPerformed(java.awt.event.ActionEvent evt)
        //  jMenuItemConnectivityActionPerformed method return type : void
        //  jMenuItemConnectivityActionPerformed method description : This method is called when the readUser clicks on the Connectivity button. It displays the Connectivity form.

        SystemSettingsConectionsForm systemSettingsConectionsForm = new SystemSettingsConectionsForm(user);
        systemSettingsConectionsForm.setVisible(rootPaneCheckingEnabled);
        // systemSettingsConectionsForm.setAlwaysOnTop(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jMenuItemConnectivityActionPerformed

    private void jMenuItemCompanyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCompanyProfileActionPerformed
        //  jMenuItemCompanyProfileActionPerformed method parameters : ActionEvent evt
        //  jMenuItemCompanyProfileActionPerformed method signature : void jMenuItemCompanyProfileActionPerformed(java.awt.event.ActionEvent evt)
        //  jMenuItemCompanyProfileActionPerformed method return type : void
        //  jMenuItemCompanyProfileActionPerformed method description : This method is called when the readUser clicks on the Company Profile button. It displays the Company Profile form.
        SystemSettingsCompanyProfileForm systemSettingsCompanyProfileForm = new SystemSettingsCompanyProfileForm(user);
        systemSettingsCompanyProfileForm.setVisible(rootPaneCheckingEnabled);
        // systemSettingsCompanyProfileForm.setAlwaysOnTop(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jMenuItemCompanyProfileActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed

         AboutForm aboutForm = new AboutForm();
            aboutForm.setVisible(true);
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jMenuItemHelpWikiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHelpWikiActionPerformed

        JOptionPane.showMessageDialog(new JFrame(), "Error!  \n " + "This feature is under Development! \n  Please contact the system developers for assistance!", "Ubiquitous System - Under Development ", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jMenuItemHelpWikiActionPerformed

    private void jMenuItemNewLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewLoanActionPerformed

        Read read = new Read();
        Book bookFromDatabase = read.loanBookByTitle();
        if (bookFromDatabase != null) {
        BookingForm bookingForm = new BookingForm(user,bookFromDatabase );
        bookingForm.setVisible(true);
        bookingForm.setAutoRequestFocus(true);
        }else{
            JOptionPane.showMessageDialog(this, "No book found with that title, please try again!");
        }

    }//GEN-LAST:event_jMenuItemNewLoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CRUDGui cRUDGui = new CRUDGui(user);
                cRUDGui.setVisible(true);
            }
        });
    }

    /**
     *
     * @return
     */
    public Image displayFrameImageIcon() {
        FrameSettings frameSettings = new FrameSettings();
        return frameSettings.frameSettingsSetIconImage();
    }

    /**
     *
     */
    public void exit() {
        // exit method parameters : none
        // exit method signature : void exit()
        // exit method return type : void
        // exit method description : This method is called when the readUser clicks on the exit button. It closes the application.
        JOptionPane.showMessageDialog(new JFrame(), "Thanks for using my program!  \n \n " + "Author : Peter Buckingham \n Student Number: ****65289 \n Date: May 2022", "Ubiquitous System - CRUD ", JOptionPane.INFORMATION_MESSAGE);
        System.out.println("");
        System.out.println("Thanks for using my program!");
        System.out.println("Author : Peter Buckingham \n");
        System.err.println("");
        System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddBook;
    private javax.swing.JButton jButtonAddUser;
    private javax.swing.JButton jButtonBookList;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDeleteBook;
    private javax.swing.JButton jButtonDeleteUser;
    private javax.swing.JButton jButtonSearchBook;
    private javax.swing.JButton jButtonSearchUser;
    private javax.swing.JButton jButtonUpdateBook;
    private javax.swing.JButton jButtonUpdateUser;
    private javax.swing.JButton jButtonUserList;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelPictureBanner;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile1;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemCRUD;
    private javax.swing.JMenuItem jMenuItemCompanyProfile;
    private javax.swing.JMenuItem jMenuItemConnectivity;
    private javax.swing.JMenuItem jMenuItemHelpWiki;
    private javax.swing.JMenuItem jMenuItemNewLoan;
    private javax.swing.JMenu jMenuSettings;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelImagePanelBanner;
    private javax.swing.JPanel jPanelTop;
    // End of variables declaration//GEN-END:variables
}
